UPDATE ARTICULOS SET DESCRIPCION_AR = 'ESCANER E IMPRESORA' WHERE CODIGO_AR =2;
--CONCATENACION PARA ACTUALIZAR COLUMNA
UPDATE ARTICULOS SET DESCRIPCION_AR = CONCAT('* ',DESCRIPCION_AR) WHERE CODIGO_AR IN (5,6);