ALTER TABLE TB_CATEGORIAS MODIFY (CODIGO_CA NOT NULL);
ALTER TABLE TB_CATEGORIAS MODIFY (DESCRIPCION NOT NULL);

ALTER TABLE TB_MEDIDAS MODIFY (CODIGO_ME NOT NULL);

ALTER TABLE ARTICULOS MODIFY (CODIGO_AR NOT NULL);

ALTER TABLE TB_MEDIDAS MODIFY (DESCRIPCION NVARCHAR2(30));
---ELIMINAR UNA COLUMNA DE LA TABLA
ALTER TABLE ARTICULOS DROP COLUMN MARCA_AR;
--ACTUALIZACION DE COLUMNA DE MODIFICACION
ALTER TABLE ARTICULOS MODIFY CODIGO_AR NUMBER(6)  DEFAULT 0;
ALTER TABLE TB_CATEGORIAS MODIFY CODIGO_CA NUMBER(6)  DEFAULT 0;
ALTER TABLE TB_MEDIDAS MODIFY CODIGO_ME NUMBER(6)  DEFAULT 0;
--AGREGAR UNA COLUMNA EN LA TABLA
ALTER TABLE ARTICULOS ADD COLUMN MARCA_AR VARCHAR(30);
ALTER TABLE ARTICULOS ADD(CODIGO_ME NUMBER(6), CODIGO_CA NUMBER(6));