SELECT * FROM tb_medidas;

SELECT CODIGO_AR,DESCRIPCION_AR FROM ARTICULOS WHERE CODIGO_CA =2;
SELECT * FROM ARTICULOS WHERE DESCRIPCION_AR='MICROONDAS';

SELECT * FROM ARTICULOS WHERE NOT DESCRIPCION_AR IN('MICROONDAS');
SELECT* FROM ARTICULOS WHERE DESCRIPCION_AR LIKE 'R%';--QUE EMPIEZEN CON LA PRIMERA LETRA R
SELECT* FROM ARTICULOS WHERE DESCRIPCION_AR LIKE '%R';--PALABR QUE LLEVE R 