CREATE TABLE TB_CATEGORIAS(
CODIGO_CA NUMBER(4),
DESCRIPCION VARCHAR2(30));

CREATE TABLE TB_MEDIDAS(
CODIGO_ME NUMBER(3),
ABREVIATURA_ME VARCHAR2(3),
DESCRIPCION VARCHAR2(20));

CREATE TABLE ARTICULOS(
CODIGO_AR NUMBER(6),
DESCRIPCION_AR VARCHAR2(50),
MARCA_AR VARCHAR2(30));