DELETE FROM ARTICULOS WHERE CODIGO_AR IN (5,6);
DELETE FROM ARTICULOS WHERE CODIGO_AR >4;
---ELIMINACION EN UNA TABLA MADRE, NO SE PUEDE POR QUE SE ESTAN UTILIZANDO EN TABLAS HIJAS NO SE PODRA ELIMINAR EL REGISTRO.
DELETE FROM TB_MEDIDAS WHERE CODIGO_ME=1;