INSERT INTO TB_CATEGORIAS(CODIGO_CA,DESCRIPCION)
                   VALUES(3,'EVENTOS');
                   
INSERT INTO TB_MEDIDAS(CODIGO_ME,ABREVIATURA_ME,DESCRIPCION)
                   VALUES(3,'MTS','METROS');

INSERT INTO ARTICULOS(CODIGO_AR,DESCRIPCION_AR,CODIGO_ME,CODIGO_CA)
                   VALUES(6,'ESCRITORIO',1,1);