--TABLA HIJA
ALTER TABLE ARTICULOS
ADD CONSTRAINT FK_01
FOREIGN KEY (CODIGO_ME) 
REFERENCES TB_MEDIDAS(CODIGO_ME);

ALTER TABLE ARTICULOS
ADD CONSTRAINT FK_02
FOREIGN KEY (CODIGO_CA) 
REFERENCES TB_CATEGORIAS(CODIGO_CA);